version: '3.7'

services:
  certdumper:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    # container_name: traefik_certdumper
    env_file:
      - .env
    network_mode: none
    volumes:
      - ./acme.json:/traefik/acme.json:ro
      - ./output:/output:rw
      - ./hook.sh:/hook/hook.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
